name: Deploy

on:
  push:
    branches:
      - main
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: flyctl deploy --app hdi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to beta
        if: github.ref == 'refs/heads/beta'
        run: flyctl deploy --app hdai-beta
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
